model_config:
  vilbert:
    training_head_type: visual7w
    num_labels: 1
    losses:
    - type: cross_entropy

dataset_config:
  hateful_memes:
    return_features_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer:
  type: adam_w
  params:
    lr: 2e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 200
    num_training_steps: ${training.max_updates}

evaluation:
  metrics:
  - accuracy

training:
  batch_size: 256
  lr_scheduler: true
  max_updates: 2000
  find_unused_parameters: true
  early_stop:
    criteria: visual7w/accuracy
    minimize: false
  evaluation_interval: 360
  evaluate_metrics: true

checkpoint:
  resume_pretrained: true
  resume_zoo: vilbert.pretrained.cc.original 
  pretrained_state_mapping:
    model.bert: model.bert
